--ilker okur
--musteri veri tabani islemleri
--DB lerde Musteri,urun,personel,kategori,satis kayitlari tutulacak
-- NOT!! Adim adim programi derleyerek ilerledigim icin derlenen kod satirlarini yorum satiri yapiyorum

--create database SatisVT

--use SatisVT
--Create Table TBLKATEGORI
--(
--KATEGORIID tinyint identity(1,1) primary key,
--KATEGORIAD varchar(50)
--)

--Create table TBLURUNLER
--(
--URUNID int identity(1,1) primary key,
--URUNAD varchar(50),
--URUNMARKA varchar(50),
--KATEGORI tinyint,
--URUNALISFIYAT decimal(18,2),
--URUNSATISFIYAT decimal(18,2),
--URUNSTOK smallint check(URUNSTOK>0),
--URUNDURUM bit default '1'
--)

--Create table TBLPERSONEL
--(
--PERSONELID smallint identity(1,1) primary key,
--PERSONELADSOYAD varchar(50)
--)

--Create table TBLMUSTERI
--(
--MUSTERIID int primary key identity(1,1),
--MUSTERIAD varchar(50),
--MUSTERISOYAD varchar(50),
--MUSTERISEHIR varchar(13),
--MUSTERIBAKIYE decimal(18,2)
--)

--Create table TBLHAREKET
--(
--HAREKETID int primary key identity(1,1),
--URUN int,
--MUSTERI int,
--PERSONEL smallint,
--ADET int,
--TUTAR decimal(18,2),
--TARIH smalldatetime
--)

--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BÝLGÝSAYAR')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EÞYA')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')
--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')

--INSERT INTO TBLURUNLER(URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK) Values ('BUZDOLABI', 'SIEMENS',2,4356,4588,10)
--------GERI KALAN URUNLERI TABLOYA ELLE GIRECEGIM

--SELECT * FROM TBLURUNLER

--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM ÜRÜN' FROM TBLURUNLER INNER JOIN TBLKATEGORI
--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID GROUP BY KATEGORIAD ORDER BY COUNT(*)

--KATEGORI ADI BÝLGÝSAYAR OLAN ÜRÜNLERE SATIS FIYATINA 500 LIRA ZAM YAPALIM

--UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI 
--WHERE KATEGORIAD= 'BÝLGÝSAYAR')

--SELECT * FROM TBLURUNLER

--
--CREATE PROCEDURE HAREKETLER
--AS
--SELECT HAREKETID, URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'AD SOYAD',
--PERSONELADSOYAD,ADET,TUTAR,TARIH
--FROM TBLHAREKET INNER JOIN TBLURUNLER
--ON TBLHAREKET.URUN=TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI
--ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL
--ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

--EXECUTE HAREKETLER

--CREATE TABLE KASA
--(
--TOPLAM decimal(18,2)
--)

--INSERT INTO KASA values (0)

--SELECT * FROM KASA

--UPDATE KASA SET TOPLAM=(SELECT SUM(TUTAR) FROM TBLHAREKET)

--SELECT * FROM TBLKATEGORI

--ALTER PROCEDURE [dbo].[TEST4]
--AS
--SELECT URUNAD,URUNMARKA,URUNSTOK,URUNSTOK=
--CASE
--WHEN URUNSTOK>=1 AND URUN STOK <=5 THEN 'KRITIK SEVIYE'
--WHEN URUNSTOK>=6 AND URUN STOK <=10 THEN 'TAKVIYE YAPILMALI'
--WHEN URUNSTOK>10 THEN 'URUN STOK SAYISI YETERLI'
--END 
--FROM TBLURUNLER

--Select KATEGORIAD, COUNT(*) FROM TBLKATEGORI INNER JOIN TBLURUNLER ON TBLKATEGORI.KATEGORIID=TBLURUNLER.KATEGORI GROUP BY KATEGORIAD



